# 开启gzip压缩功能
gzip on;

# 设置触发gzip压缩的最小文件大小为1kB
gzip_min_length 1k;

# 设置gzip压缩时使用的缓冲区大小和数量
gzip_buffers 4 16k;

# 该行已被注释掉，用于设置响应HTTP版本，默认1.1，1.0较少使用
#gzip_http_version 1.0;

# 设置gzip压缩级别为6（1最快，9最佳压缩）
gzip_comp_level 6;

# 定义哪些类型的响应可以被压缩
gzip_types text/plain application/javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;

# 关闭gzip的Vary头（影响代理缓存）
gzip_vary off;

# 禁用针对旧版本IE浏览器的gzip压缩
gzip_disable "MSIE [1-6]\.";

# 配置一个监听80端口的服务器
server {
    listen       80;
    server_name  localhost; # 设置服务器名称为localhost

    # 主目录位置配置
    location / {
        add_header    Cache-Control  max-age=3600; # 设置HTTP缓存控制头，缓存时间为3600秒
        root   /usr/share/nginx/html; # 设置网站的根目录
        try_files $uri $uri/ /index.html; # 尝试传递请求到文件，如果文件或目录不存在则返回index.html
	}

    # 定义处理404错误的位置
    location /404 {
        # 如果进入此位置，则返回404状态码，表示资源未找到
        return 404 ;
    }
}
